# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GoReleaserTestingAT004 < Formula
  desc "Testing out uploading a brew forumla to a public tap"
  homepage "https://twitter.com/YrrepNoj"
  version "0.0.4"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/YrrepNoj/go-releaser-testing/releases/download/v0.0.4/go-releaser-testing_0.0.5-next_Darwin_arm64"
      sha256 "e40250d9495a31fe14dbda8bab499149f9d2ea75a97238a9d1fa8ea855d39c25"

      def install
        bin.install "go-releaser-testing_0.0.5-next_Darwin_arm64" => "go-releaser-testing"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/YrrepNoj/go-releaser-testing/releases/download/v0.0.4/go-releaser-testing_0.0.5-next_Darwin_x86_64"
      sha256 "aa6fb18e9128edbbe192c7deb53203730535216204a2b2216af32a95e1cba3b5"

      def install
        bin.install "go-releaser-testing_0.0.5-next_Darwin_x86_64" => "go-releaser-testing"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/YrrepNoj/go-releaser-testing/releases/download/v0.0.4/go-releaser-testing_0.0.5-next_Linux_arm64"
      sha256 "38c5b73cae43af4e5616fb954c5d9d25d438f7d169fcd2eaf2f916e7973af5b0"

      def install
        bin.install "go-releaser-testing_0.0.5-next_Linux_arm64" => "go-releaser-testing"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/YrrepNoj/go-releaser-testing/releases/download/v0.0.4/go-releaser-testing_0.0.5-next_Linux_x86_64"
      sha256 "a7473ae2cc7c66f0cbea0c424fd62326379a26cb184099e220f97626101c0e9c"

      def install
        bin.install "go-releaser-testing_0.0.5-next_Linux_x86_64" => "go-releaser-testing"
      end
    end
  end
end
