# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GoReleaserTesting < Formula
  desc "Testing out uploading a brew forumla to a public tap"
  homepage "https://twitter.com/YrrepNoj"
  version "0.0.5"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/YrrepNoj/go-releaser-testing/releases/download/v0.0.5/go-releaser-testing_0.0.5_Darwin_arm64"
      sha256 "08b6765b2e3d94bb81b10dcd9caa42f73eec3b4be34be83234fe1a38c7d15a69"

      def install
        bin.install "go-releaser-testing_0.0.5_Darwin_arm64" => "go-releaser-testing"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/YrrepNoj/go-releaser-testing/releases/download/v0.0.5/go-releaser-testing_0.0.5_Darwin_x86_64"
      sha256 "bdea174829aaf74c5852a0073cebbfe47a4754d42c6e0b352117c2c3d7904201"

      def install
        bin.install "go-releaser-testing_0.0.5_Darwin_x86_64" => "go-releaser-testing"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/YrrepNoj/go-releaser-testing/releases/download/v0.0.5/go-releaser-testing_0.0.5_Linux_arm64"
      sha256 "e9699280337c5ea10523ae7e266865df6b157aa7a856265c9c48182821702590"

      def install
        bin.install "go-releaser-testing_0.0.5_Linux_arm64" => "go-releaser-testing"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/YrrepNoj/go-releaser-testing/releases/download/v0.0.5/go-releaser-testing_0.0.5_Linux_x86_64"
      sha256 "35a349c719ebc8f4338686a8e01c349d3b64b0d033559f7f7aa72b854557c789"

      def install
        bin.install "go-releaser-testing_0.0.5_Linux_x86_64" => "go-releaser-testing"
      end
    end
  end
end
