# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GoReleaserTesting@v0191 < Formula
  desc "Testing out uploading a brew forumla to a public tap"
  homepage "https://twitter.com/YrrepNoj"
  version "v0.19.1"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/YrrepNoj/go-releaser-testing/releases/download/v0.0.4/go-releaser-testing_0.0.4_Darwin_arm64"
      sha256 "09b6f0e728cec07f30034afd8422c7404792a43b161afb5d6a7a1e32cb651336"

      def install
        bin.install "go-releaser-testing_0.0.5-next_Darwin_arm64" => "go-releaser-testing"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/YrrepNoj/go-releaser-testing/releases/download/v0.0.4/go-releaser-testing_0.0.4_Darwin_x86_64"
      sha256 "4bd69c9a7bcab0fa05ea8b4c19300443f29be25e188ccbd551fba42ed0075b29"

      def install
        bin.install "go-releaser-testing_0.0.4_Darwin_x86_64" => "go-releaser-testing"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/YrrepNoj/go-releaser-testing/releases/download/v0.0.4/go-releaser-testing_0.0.5-next_Linux_arm64"
      sha256 "38c5b73cae43af4e5616fb954c5d9d25d438f7d169fcd2eaf2f916e7973af5b0"

      def install
        bin.install "go-releaser-testing_0.0.5-next_Linux_arm64" => "go-releaser-testing"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/YrrepNoj/go-releaser-testing/releases/download/v0.0.4/go-releaser-testing_0.0.5-next_Linux_x86_64"
      sha256 "a7473ae2cc7c66f0cbea0c424fd62326379a26cb184099e220f97626101c0e9c"

      def install
        bin.install "go-releaser-testing_0.0.5-next_Linux_x86_64" => "go-releaser-testing"
      end
    end
  end
end
